#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHANGELOG="${REPO_ROOT}/CHANGELOG.md"
WAIVERS="${REPO_ROOT}/waivers.yaml"
OUTPUT=".github/copilot-instructions.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# Make output path absolute if relative (relative to cwd)
if [[ "${OUTPUT}" != /* ]]; then
  OUTPUT="${PWD}/${OUTPUT}"
fi

# Parse waived rule IDs from waivers.yaml (if present)
WAIVED_IDS=()
if [[ -f "${WAIVERS}" ]]; then
  mapfile -t WAIVED_IDS < <(
    python3 - <<'PYEOF' "${WAIVERS}"
import sys, re
try:
    with open(sys.argv[1], encoding="utf-8") as f:
        content = f.read()
    for m in re.finditer(r'rule_id:\s*([A-Z]+-\d+)', content):
        print(m.group(1))
except Exception:
    sys.exit(0)
PYEOF
  )
fi

is_waived() {
  local id="$1"
  for w in "${WAIVED_IDS[@]+"${WAIVED_IDS[@]}"}"; do
    [[ "$w" == "$id" ]] && return 0
  done
  return 1
}

# Extract BLOCK-level rules from CHANGELOG.md
# Format in changelog: `RULE-ID` BLOCK — Description
declare -A DOMAIN_RULES
DOMAIN_ORDER=(TDD ARCH TYPE NAME SIZE DEAD TEST SEC DEP OBS)
for d in "${DOMAIN_ORDER[@]}"; do DOMAIN_RULES[$d]=""; done

while IFS= read -r line; do
  # Match lines like: - `TYPE-1` BLOCK — Description
  if [[ "$line" =~ \`([A-Z]+-[0-9]+)\`\ BLOCK\ —\ (.+) ]]; then
    rule_id="${BASH_REMATCH[1]}"
    description="${BASH_REMATCH[2]}"
    domain="${rule_id%%-*}"
    if ! is_waived "$rule_id" && [[ -v DOMAIN_RULES[$domain] ]]; then
      DOMAIN_RULES[$domain]+="${rule_id}|${description}"$'\n'
    fi
  fi
done <"${CHANGELOG}"

# Section headers per domain
declare -A DOMAIN_HEADERS
DOMAIN_HEADERS[TDD]="Test-First Development"
DOMAIN_HEADERS[ARCH]="Architecture"
DOMAIN_HEADERS[TYPE]="Type Safety"
DOMAIN_HEADERS[NAME]="Naming"
DOMAIN_HEADERS[SIZE]="Size Limits"
DOMAIN_HEADERS[DEAD]="Dead Code"
DOMAIN_HEADERS[TEST]="Test Quality"
DOMAIN_HEADERS[SEC]="Security"
DOMAIN_HEADERS[DEP]="Dependencies"
DOMAIN_HEADERS[OBS]="Observability"

mkdir -p "$(dirname "${OUTPUT}")"

VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1], encoding="utf-8"))["version"])' "${REPO_ROOT}/package.json")"

RULE_COUNT=0
{
  cat <<HEADER
# Coding Instructions
<!-- Generated by clean-code-codex v${VERSION}. Do not edit manually.
     Run: bash scripts/generate-instructions.sh to regenerate. -->

HEADER

  for domain in "${DOMAIN_ORDER[@]}"; do
    rules="${DOMAIN_RULES[$domain]}"
    [[ -z "$rules" ]] && continue

    echo "## ${DOMAIN_HEADERS[$domain]}"
    while IFS='|' read -r rule_id description; do
      [[ -z "$rule_id" ]] && continue
      echo "- ${description} (${rule_id})."
      ((RULE_COUNT++)) || true
    done <<<"$rules"
    echo
  done
} >"${OUTPUT}"

echo "Generated ${OUTPUT} with ${RULE_COUNT} rules"
