#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1], encoding="utf-8"))["version"])' "${REPO_ROOT}/package.json")"
OUTPUT=".github/workflows/codex.yml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# Make output path absolute if relative (relative to cwd)
if [[ "${OUTPUT}" != /* ]]; then
  OUTPUT="${PWD}/${OUTPUT}"
fi

mkdir -p "$(dirname "${OUTPUT}")"

# Single-quoted heredoc prevents shell interpolation of ${{ }} expressions
cat >"${OUTPUT}" <<'EOF'
# Generated by clean-code-codex v__VERSION__. Do not edit manually.
# Run: bash scripts/generate-workflow.sh to regenerate.
name: Clean Code Codex

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan-secrets:
    name: SEC-1 — Secret Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Scan for secrets
        run: |
          git diff origin/${{ github.base_ref }}...HEAD --name-only | \
          while IFS= read -r file; do
            [ -f "$file" ] || continue
            python3 -c "import json,sys; p=sys.argv[1]; print(json.dumps({'tool_name':'Write','tool_input':{'file_path':p,'content':open(p, encoding='utf-8', errors='replace').read()}}))" "$(pwd)/$file" | bash hooks/scripts/hook-sec-write.sh
          done

  check-dead-code:
    name: DEAD-2/3 — Dead Code
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python3 scripts/lint_dead_code.py --path .

  check-function-size:
    name: SIZE-1 — Function Size
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Check function size on changed files
        run: |
          git diff origin/${{ github.base_ref }}...HEAD --name-only | \
          (grep -E '\.(py|ts|tsx|js|jsx|mjs|cjs|go|rs|sh)$' || true) | \
          while IFS= read -r file; do
            [ -f "$file" ] || continue
            python3 -c "import json,sys; p=sys.argv[1]; print(json.dumps({'tool_name':'Edit','tool_input':{'file_path':p,'content':open(p, encoding='utf-8', errors='replace').read()}}))" "$(pwd)/$file" | bash hooks/scripts/hook-quality.sh
          done

  check-dependencies:
    name: DEP-1 — Vulnerability Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: bash scripts/dep_audit.sh --path .
EOF

python3 - <<'PYEOF' "${OUTPUT}" "${VERSION}"
from pathlib import Path
import sys

output_path = Path(sys.argv[1])
version = sys.argv[2]
output_path.write_text(output_path.read_text().replace('__VERSION__', version), encoding='utf-8')
PYEOF

echo "Generated ${OUTPUT}"
